exports.toDoListPage = function(list_todo, list_done, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>ToDo List</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1>To Do List
                    </h1>
                </header>

                <div class="w3-container">
                <form class="w3-container" id="form" action="/adiciona" method="POST">
                    <p>
                        <label class="w3-text-teal"><b>Tarefa</b></label>
                        <input class="w3-input w3-border w3-light-grey" name="what" type="text" required>
                    </p>
                    <p>
                        <label class="w3-text-teal"><b>Data</b></label>
                        <input class="w3-input w3-border w3-light-grey" name="dateDued" type="date" required>
                    </p>
                    <p>
                        <label class="w3-text-teal"><b>Quem?</b></label>
                        <input class="w3-input w3-border w3-light-grey" name="who" type="text" required>
                    </p>
                    <input type="hidden" name="id" value=""/>
                    <p>
                        <input class="w3-btn w3-blue" type="submit" value="Registar">
                    </p>
                </form>
                </div>
            </div>
            <div class="w3-row">
                <div class="w3-half">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Tarefa</th><th>Quem</th><th>Quando</th>
                            <th></th>
                        </tr>
                `
    for(let i=0; i < list_todo.length; i++){
        pagHTML += `
                <tr>
                    <td>${list_todo[i].id}</td>
                    <td>
                        <a>${list_todo[i].dateDued}</a>
                    </td>
                    <td>
                        <a>${list_todo[i].who}</a>
                    </td>
                    <td>
                        <a>${list_todo[i].what}</a>
                    </td>
                    <td>
                            <form action="/concluir" method="POST">
                                <input type="hidden" name="id" value="${list_todo[i].id}"/>
                                <button class="w3-btn w3-green" type="submit">Concluído</button>
                            </form>
                            <form action="/eliminar" method="POST">
                                <input type="hidden" name="id" value="${list_todo[i].id}"/>
                                <button class="w3-btn w3-red" type="submit">Eliminar</button>
                            </form>
                        </td>  
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
            <div class="w3-half">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Tarefa</th><th>Quem</th><th>Quando</th>
                            <th></th>
                        </tr>
                `
    for(let i=0; i < list_done.length; i++){
        pagHTML += `
                <tr>
                    <td>${list_done[i].id}</td>
                    <td>
                        <a>${list_done[i].what}</a>
                    </td>
                    <td>
                        <a>${list_done[i].who}</a>
                    </td>
                    <td>
                        <a>${list_done[i].dateDued}</a>
                    </td>
                    <td>
                            <form action="/eliminar" method="POST">
                                <input type="hidden" name="id" value="${list_done[i].id}"/>
                                <button class="w3-btn w3-red" type="submit">Eliminar</button>
                            </form>
                            <button class="w3-btn w3-blue" onclick="editar('${list_done[i].id}','${list_done[i].what}','${list_done[i].who}','${list_done[i].dateDued}')">Editar</button>
                        </td>  
                </tr>
        `
    }
    

    pagHTML += `
            </table>
            </div>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by RPCW2023 in ${d}</h5>
                </footer>
            </div>
            <script>
                function editar(id, what, who, dateDued){
                    if(document.getElementById("form").id.value != ""){
                        document.getElementById("form").id.value = ""
                        document.getElementById("form").what.value = ""
                        document.getElementById("form").who.value = ""
                        document.getElementById("form").dateDued.value = ""
                        document.getElementById("form").action = "/adiciona"
                    }
                    else{
                        document.getElementById("form").action = "/editar"
                        document.getElementById("form").id.value = id
                        document.getElementById("form").what.value = what
                        document.getElementById("form").who.value = who
                        document.getElementById("form").dateDued.value = dateDued
                    }
                }
            </script>
        </body>
    </html>
    `
    return pagHTML
}